name: CI/CD Backend & Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_TAG: latest
  BACKEND_IMAGE: cristianboni22/backend-app
  FRONTEND_IMAGE: cristianboni22/frontend-app

jobs:

  # ----------------------
  # TEST BACKEND
  # ----------------------
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install backend dependencies
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/backend" >> $GITHUB_ENV

      - name: Run backend tests
        run: |
          python -m unittest discover -s backend/tests -p "test_*.py" -v

  # ----------------------
  # TEST FRONTEND
  # ----------------------
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npx jest --watchAll=false

  # ----------------------
  # BUILD & PUSH DOCKER IMAGES
  # ----------------------
  build-and-push:
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Login Docker Hub usando la Action oficial
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build & Push Backend
      - name: Build & Push Backend Image
        run: |
          docker build -t $BACKEND_IMAGE:$IMAGE_TAG ./backend
          docker push $BACKEND_IMAGE:$IMAGE_TAG

      # Build & Push Frontend
      - name: Build & Push Frontend Image
        run: |
          docker build -t $FRONTEND_IMAGE:$IMAGE_TAG ./frontend
          docker push $FRONTEND_IMAGE:$IMAGE_TAG
